language: php

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 5

sudo: false

php:
  - 5.6
  - 7
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --allow-risky true --diff --verbose
